### ISSUE TITLE
Vertical alignment bug when using cylinder shape with rectangles

### ISSUE THREAD

**Issue by Ninju** [FundingCircle/fc4-framework#149]
The issue can in this diagram:
https://github.com/FundingCircle/docs/blob/a3704fe49ee0098b56f0a11d775227b2a8c1e9a1/diagrams/fc4/global/originations_api/originations_api_02_container_planned.png

Here is the corresponding YAML: 
https://github.com/FundingCircle/docs/blob/a3704fe49ee0098b56f0a11d775227b2a8c1e9a1/diagrams/fc4/global/originations_api/originations_api_02_container_planned.yaml

**Comment by aviflax** [comment]
Thanks for the bug report!

I took a second look at this and now it looks like we were mistaken; I think the only issue with the diagram is that the _Web Process_ container and the _Consumer Process_ container _together_ are not centered; we can fix this by either moving the one on the left more to the right, or vice-versa.

I tried moving the _Web Process_ container 100px to the left and it all looks right at that point:

![originations_api_02_container_planned with layout tweaked by Avi](https://user-images.githubusercontent.com/141844/54378576-f6eada00-465d-11e9-982d-332c39561d29.png)

(I added the overlay so we could more easily see that everything is aligned.)

(Of course if you prefer a little more whitespace you could move the _Consumer Process_ 100px to the right instead.)

At this point the only reason I can think that we both _thought_ we observed a bug is that we were rushing that morning, because we were tight for time.

I’m closing this for now but please let me know if you think I’ve missed something.

Thanks!
