### ISSUE TITLE
EP05: Unified Authoring Workflow are no longer final

### ISSUE THREAD

**Issue by miketheman** [FundingCircle/fc4-framework#191]
The "EP05: Unified Authoring Workflow" states that there will be a `fc4 edit...` functionality.

On the latest release, this message is returned:

```shellsession
$ fc4 edit diagrams/some.yaml
The subcommand `edit` is no longer supported. Equivalent behavior can be invoked via:
  fc4 -fsrw PATH [PATH...]
For more information please run `fc4 --help` and/or see https://git.io/fjVkL
```

The URL points the user to the issue in discussion - #168, but the existing docs and decisions in the repo are now outdated and haven't been superseded with a new EP.

Should the EP be modified/superseded with a new one based on that issue?

**Comment by aviflax** [comment]
Hi Mike, thanks for pointing this out!

This reveals two things to me:

* I’ve been thinking of the Enhancement Proposals as historical artifacts that would be applicable for only a limited term after their publication, and I’d erroneously, unknowingly, assumed that others would see them that way as well.
  * Now that you’ve pointed this out, though, I see that that is a bad assumption, and that it might be better to think of the EPs as being “in force” indefinitely until they are explicitly replaced, superseded, or retired. This would be more consistent with the Python Enhancement Proposal (PEP) process (as defined in [PEP 1](https://www.python.org/dev/peps/pep-0001/)) which as per [EP0](https://github.com/FundingCircle/fc4-framework/blob/94f02211e809d73d5b6b60d1ea4e8f0241162c37/proposals/ep00-enhancement-proposals/ep00-enhancement-proposals.md) was the inspiration for our EP process.
  * It does seem clear to me though that we need to more clearly and consistently treat the corpus of EPs as _either_ documentation that should be maintained, or moment-in-time discussions of changes that become obsolete fairly quickly.
  * What do you think? I can see advantages in either direction.
* I didn’t write an EP for the CLI change, and I should have.
  * Sorry about that.
    * (My motivation for instituting the EP process was to create more opportunities for the maintainers and users of this framework to collaborate and engage with each other, and I think I’d become a bit discouraged by the lack of engagement lately, and the slow growth in the user base. That’s not a good reason to become lax though.)
  * I’m thinking it might be worthwhile to write a retroactive EP now, so as to (a) document the change more thoroughly and clearly, and (b) show some respect for the EP process ensure that future significant changes _are_ discussed via EPs before being shipped
  * I’ll also write up an EP now for [the project](https://github.com/FundingCircle/fc4-framework/projects/2) I’ve been working on to replace the Node-based renderer with a faster, simpler, more integrated Clojure-based renderer.

Does that all make sense? I’d love to hear your thoughts on all of this — and thanks again for the feedback, I really appreciate it!

**Comment by miketheman** [comment]
Hey @aviflax ! Glad to keep the ideas flowing. I think I was reading into the EPs similar to your callout of PEPs, RFCs, and probably ADRs too - all of these are meant to be the topic of discussion and once "accepted" or "implemented" are the standards, needed a superseding one when that changes.
I might think of that akin to a behavioral test - if the assumptions that we knew before have changed, and we change the underlying code, the test ought to break and expose the change in expectation.

I'm a big fan of "tests expressing the desired behaviors" - but those are typically specific to a given subset of functionality, and don't always encompass the behavior of a larger system. We've been trying out ADRs, and the biggest challenge has been "when do I write one?"
The general feeling I've got is "when you're proposing a shift that changes more than a unit/function that changes behavior beyond the scope of a component" (which is pretty fuzzy 😀 ).

As with any process, as long as we do our best to convey the approach and set the expectations for others, I'm happy to continue to evolve it - so maybe a precursor is to revisit [EP00](https://github.com/FundingCircle/fc4-framework/blob/c7019cb83a014982e978947740e17b7842563f40/proposals/ep00-enhancement-proposals/ep00-enhancement-proposals.md) and determine how they would best apply to this project and process.

One big question would be: should an EP be allowed to be changed after it's merged to `master` and is `final`? (Typos, slight mis-wordings, template style updated, etc)

**Comment by aviflax** [comment]
Thanks Mike! I really appreciate your thoughts on this!

(And sorry to take so long to follow-up; as I mentioned in our Twitter DM thread I was on holiday last week.)

Here’s where my head is at: I think the process proposed in EP00 was premature. At the time I had lots of ideas for different aspects of the framework to work on, and I wanted some framework for manifesting and engaging the latent user community to get their feedback on what I should work on. 

I think it the approach I took was premature because:

1. There really wasn’t much of a user community at the time, and there still isn’t
1. The project was and is still fairly young and needs to be nimble (dare I say, “agile”)

I think if there was a “discussions” tab in GitHub I wouldn’t have bothered to propose the EP process; I would have simply used that tab, and it would have been better. Among other advantages, such discussions wouldn’t have automatically implied any kind of permanence or standard-setting. Many projects hosted by GitHub use Issues to host discussions, but I’m stubborn about semantics — to my own detriment.

So, I’m thinking that the project is too immature to involve standards that would be effective indefinitely and would need to be updated or superseded before the project can deviate from them. I think it would be better served by discussions and proposals that are firmly rooted in their temporal context, and apply only to a particular point in time.

What do you think?

(If you agree, my inclination would be to retire EP00 and the EP process, and use Issues for proposals and discussions, for now. (And document this in the project README and other places.) (If and when the community grows, we could apply for [a free Discourse instance](https://free.discourse.group) — I ❤️ Discourse.))
