### ISSUE TITLE
fc4 -h takes a long time

### ISSUE THREAD

**Issue by miketheman** [FundingCircle/fc4-framework#233]
I often run a tool with `-h` for general help, and see how to use a tool.

Running:

```shellsession
$ time fc4 -h 2&>1 >/dev/null

real	0m8.649s
user	0m12.250s
sys	0m0.584s
```

Should it take 8 seconds to read the help?

**Comment by aviflax** [comment]
Thanks for the bug report Mike!

No, it shouldn’t.

I think this is _mostly_ a dup of #219. I mean, I guess we _could_ optimize this specific case, as a kind of a stopgap measure, by having the `fc4` wrapper script print out the usage information and then exit, never having started the JVM at all. I’m open to doing that at some point, but my inclination is to try to find a more general fix before implementing stopgap measures.

I mentioned in #219 that compiling a native executable via GraalVM seems most promising to me, and I have spent some time recently (about 3 weeks ago) trying again to make that work. As per https://github.com/taylorwood/clj.native-image/issues/15 I have not yet succeeded, but I am definitely interested in revisiting this work in the next month or two.

What do you think?

**Comment by miketheman** [comment]
That makes a lot of sense - it starts to bring up a question of whether Clojure is a good use for a command line tool. I found an older thread on the topic: https://clojureverse.org/t/tricks-to-make-clojure-startup-time-faster/1176 - one idea is a "fast" CLI wrapper, that when invoing an actual command, spins up the JVM.
Another: https://clojurescript.org/guides/native-executables for ClojureScript (I don't know the difference yet between Clojure and ClojureScript ...)
If GraalVM is an easy step to create an executable that runs fast, then I'm all for it!

**Comment by aviflax** [comment]
Agreed.

I’m not 100% sure about this, but I _suspect_ that we should probably _either_ ship an AOT-compiled native binary via GraalVM, _or_ port to ClojureScript so we can use Planck/Lumo/etc. 

(Porting to ClojureScript is also intruiging because we could then use [Puppeteer](https://github.com/puppeteer/puppeteer/blob/master/README.md) to control Chromium/Chrome rather than [clj-chrome-devtools](https://github.com/tatut/clj-chrome-devtools) (which is a good library but not nearly as mature nor full-featured as Puppeteer).)

**Comment by aviflax** [comment]
Dup of #219.
