### ISSUE TITLE
Build base test/build image in CI rather than Quay

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4-framework#96]
Suggested by @sgerrand [here](https://github.com/FundingCircle/fc4-framework/pull/95#discussion_r234763615).

**Comment by aviflax** [comment]
@sgerrand I’m happy to do this, I just have a few questions first:

1. I can imagine a few different possible motivations for this, but I’m curious what reasons _you_ have in mind. Why do you think it’d be better to build the base image in CI rather than Quay?
2. When I start thinking about _how_ to do so, I get a little mixed up in my head:
   1. It’s a little tricky to me because when defining a CI job one has to choose a base image for _that_ — for the job. So I’ll need to choose + declare a base image to use to… build the base image for… building the tool itself.
   1. It may be a bit too many layers of turtles for my pea-brain.
   1. I won’t let that stop me from trying, though.
   1. So I guess I’ll want to have a job — the “left-most” job in the CI workflow that’d be responsible for building the base image that all the other jobs will use, and… publishing it to Quay if it’s changed? I guess I’d only want to build the base image at all if something about it has changed, so I’ll want to cache something? Not sure what I could cache… I’m sure there are ways of just checking directly whether the relevant `Dockerfile` has changed in the given branch/merge.
    1. I guess the above is just me thinking out loud, messily. Perhaps it’d be better if you could point me to an example of a project that already does this well?

**Comment by sgerrand** [comment]
> Why do you think it’d be better to build the base image in CI rather than Quay?

Primarily because you'll have more control over the image build and usage steps. You can control which branch will build the image – you'd previously mentioned that you thought it was wasteful to push Docker image tags for every branch/commit which are pushed to this repository.

It'll also help with debugging issues with Docker image builds, like the issues with environment variables in the image build [that you mentioned previously](https://github.com/FundingCircle/fc4-framework/pull/95#discussion_r234759145).

**Comment by sgerrand** [comment]
I don't have time to work on this now, but am happy to discuss it further next week.

**Comment by aviflax** [comment]
Cool, thanks!

**Comment by aviflax** [comment]
This is obsolete; as of #196 we’re no longer using our own custom Docker images for our CI jobs.
